/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import konfigurasi.koneksi;

/**
 *
 * @author user
 */
public class FormLogin extends javax.swing.JFrame {
  

 
    /**
     * Creates new form FormLogin
     */
    
    public FormLogin() {
        initComponents();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_password = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField_password = new javax.swing.JPasswordField();
        jPanel_batal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_masuk = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 180, 20));

        jTextField_username.setBorder(null);
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });
        jTextField_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_usernameKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, 20));

        jPasswordField_password.setBorder(null);
        jPasswordField_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_passwordKeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, 20));

        jPanel_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_batalMouseClicked(evt);
            }
        });

        jLabel6.setText("batal");

        javax.swing.GroupLayout jPanel_batalLayout = new javax.swing.GroupLayout(jPanel_batal);
        jPanel_batal.setLayout(jPanel_batalLayout);
        jPanel_batalLayout.setHorizontalGroup(
            jPanel_batalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_batalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel_batalLayout.setVerticalGroup(
            jPanel_batalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_batalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, 40));

        btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masukMouseClicked(evt);
            }
        });
        btn_masuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("masuk");
        btn_masuk.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 11, -1, -1));

        jPanel1.add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 90, 40));
        jPanel1.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 200, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 200, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 200, 10));

        jLabel7.setText("PASSWORD    :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel8.setText("USERNAME      :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void btn_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseClicked
        // TODO add your handling code here:
        if(jTextField_username.getText().trim().isEmpty() && jPasswordField_password.getText().trim().isEmpty()){
            lbl_username.setText("username kosong");
            lbl_password.setText("password kosong");
        }
        else if(jTextField_username.getText().trim().isEmpty()){
             lbl_username.setText("username kosong");
        }
        else if (jPasswordField_password.getText().trim().isEmpty()){
              lbl_password.setText("password kosong");
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/data_depot","root","");
            String sql = " Select * from tb_user where username=? and password=? ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, jTextField_username.getText());
            pst.setString(2, jPasswordField_password.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showConfirmDialog(null, "Username dan password sama");
                FormUtama utama = new FormUtama();
                utama.setVisible(true);
                setVisible(false); 
            }
            else{
                JOptionPane.showConfirmDialog(null, "Username dan password tidak sama");
                jTextField_username.setText("");
                jPasswordField_password.setText("");
            }
            con.close();
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
        
    }//GEN-LAST:event_btn_masukMouseClicked

    private void jTextField_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usernameKeyReleased
        // TODO add your handling code here:
        lbl_username.setText("");
        
    }//GEN-LAST:event_jTextField_usernameKeyReleased

    private void jPasswordField_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_passwordKeyReleased
        // TODO add your handling code here:
        lbl_password.setText("");
    }//GEN-LAST:event_jPasswordField_passwordKeyReleased

    private void jPanel_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_batalMouseClicked
        // TODO add your handling code here:
        jTextField_username.setText("");
        jPasswordField_password.setText("");
    }//GEN-LAST:event_jPanel_batalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_masuk;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_batal;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    // End of variables declaration//GEN-END:variables
}
