/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konfigurasi.koneksi;
import konfigurasi.DBkoneksi;
/**
 *
 * @author user
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    
    private DefaultTableModel DftTblModel_langganan;
    private String SQL;
    public FormUtama() {
        initComponents();
        this.TampilData();
    }
    
    
    public void TampilData() {
        DftTblModel_langganan = new DefaultTableModel();
        DftTblModel_langganan.addColumn("IDLANGGANAN");
        DftTblModel_langganan.addColumn("NAMA");
        DftTblModel_langganan.addColumn("JENIS KELAMIN");
        DftTblModel_langganan.addColumn("TELEPON");
        DftTblModel_langganan.addColumn("ALAMAT");
        DftTblModel_langganan.addColumn("JENIS TEMPAT");
        jTable_langganan.setModel(DftTblModel_langganan);
        Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from tb_langganan";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_langganan.addRow(new Object[]{
                    res.getString("IDLANGGANAN"),
                    res.getString("NAMA"),
                    res.getString("JENIS_KELAMIN"),
                    res.getString("TELEPON"),
                    res.getString("ALAMAT"),
                    res.getString("JENIS_TEMPAT")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_frem = new javax.swing.JPanel();
        jPanel_pelanggan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_langganan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_nama = new javax.swing.JTextField();
        jTextField_telepon = new javax.swing.JTextField();
        jTextField_alamat = new javax.swing.JTextField();
        jTextField_tempat = new javax.swing.JTextField();
        jComboBox_kelamin = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        Form_nota = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_id1 = new javax.swing.JTextField();
        jTextField_nama1 = new javax.swing.JTextField();
        jTextField_jumlah1 = new javax.swing.JTextField();
        jTextField_total1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_nota = new javax.swing.JTable();
        jPanel_add = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel_save = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel_update = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel_delete = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jDateChooser_tgl1 = new com.toedter.calendar.JDateChooser();
        btn_menu = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        panel_menu = new javax.swing.JPanel();
        btn_pelanggan = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btn_nota = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_frem.setPreferredSize(new java.awt.Dimension(949, 450));
        panel_frem.setLayout(new java.awt.CardLayout());

        jTable_langganan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_langganan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_langgananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_langganan);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM DATA PELANGGAN");

        jLabel2.setText("ID PELANGGAN");

        jLabel3.setText("NAMA");

        jLabel4.setText("JENIS KELAMIN");

        jLabel5.setText("TELEPON");

        jLabel6.setText("ALAMAT");

        jLabel7.setText("JENIS TEMPAT");

        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jTextField_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_namaActionPerformed(evt);
            }
        });

        jTextField_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_teleponActionPerformed(evt);
            }
        });

        jTextField_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_alamatActionPerformed(evt);
            }
        });

        jTextField_tempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tempatActionPerformed(evt);
            }
        });

        jComboBox_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LAKI-LAKI", "PEREMPUAN" }));

        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_pelangganLayout = new javax.swing.GroupLayout(jPanel_pelanggan);
        jPanel_pelanggan.setLayout(jPanel_pelangganLayout);
        jPanel_pelangganLayout.setHorizontalGroup(
            jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pelangganLayout.createSequentialGroup()
                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_pelangganLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel_pelangganLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_pelangganLayout.createSequentialGroup()
                                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_pelangganLayout.createSequentialGroup()
                                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel_pelangganLayout.createSequentialGroup()
                                            .addComponent(jComboBox_kelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(1, 1, 1)))
                                    .addGroup(jPanel_pelangganLayout.createSequentialGroup()
                                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_delete)))))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel_pelangganLayout.setVerticalGroup(
            jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_save)
                    .addComponent(btn_update)
                    .addComponent(btn_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_frem.add(jPanel_pelanggan, "card2");

        Form_nota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("FORM NOTA PEMBAYARAN");
        Form_nota.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 25, -1, -1));

        jLabel13.setText("ID LANGGANAN");
        Form_nota.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 68, -1, -1));

        jLabel14.setText("NAMA");
        Form_nota.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 112, -1, -1));

        jLabel15.setText("TANGGAL");
        Form_nota.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel16.setText("JUMLAH GALON");
        Form_nota.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        jLabel17.setText("TOTAL HARGA");
        Form_nota.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jTextField_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_id1ActionPerformed(evt);
            }
        });
        Form_nota.add(jTextField_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 252, -1));

        jTextField_nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nama1ActionPerformed(evt);
            }
        });
        Form_nota.add(jTextField_nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 252, -1));

        jTextField_jumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_jumlah1ActionPerformed(evt);
            }
        });
        Form_nota.add(jTextField_jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 252, -1));

        jTextField_total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_total1ActionPerformed(evt);
            }
        });
        Form_nota.add(jTextField_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 252, -1));

        jTable_nota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_nota);

        Form_nota.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 334, 782, 110));

        jPanel_add.setBackground(new java.awt.Color(102, 102, 255));
        jPanel_add.setPreferredSize(new java.awt.Dimension(99, 33));

        jLabel18.setText("ADD");

        javax.swing.GroupLayout jPanel_addLayout = new javax.swing.GroupLayout(jPanel_add);
        jPanel_add.setLayout(jPanel_addLayout);
        jPanel_addLayout.setHorizontalGroup(
            jPanel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel18)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel_addLayout.setVerticalGroup(
            jPanel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_addLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        Form_nota.add(jPanel_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 290, -1, -1));

        jPanel_save.setBackground(new java.awt.Color(102, 102, 255));
        jPanel_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_saveMouseClicked(evt);
            }
        });

        jLabel19.setText("SAVE");

        javax.swing.GroupLayout jPanel_saveLayout = new javax.swing.GroupLayout(jPanel_save);
        jPanel_save.setLayout(jPanel_saveLayout);
        jPanel_saveLayout.setHorizontalGroup(
            jPanel_saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_saveLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel19)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel_saveLayout.setVerticalGroup(
            jPanel_saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_saveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Form_nota.add(jPanel_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 287, -1, -1));

        jPanel_update.setBackground(new java.awt.Color(102, 102, 255));

        jLabel20.setText("UPDATE");

        javax.swing.GroupLayout jPanel_updateLayout = new javax.swing.GroupLayout(jPanel_update);
        jPanel_update.setLayout(jPanel_updateLayout);
        jPanel_updateLayout.setHorizontalGroup(
            jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_updateLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel20)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel_updateLayout.setVerticalGroup(
            jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_updateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Form_nota.add(jPanel_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 287, -1, -1));

        jPanel_delete.setBackground(new java.awt.Color(102, 102, 255));
        jPanel_delete.setPreferredSize(new java.awt.Dimension(99, 33));

        jLabel21.setText("DELETE");

        javax.swing.GroupLayout jPanel_deleteLayout = new javax.swing.GroupLayout(jPanel_delete);
        jPanel_delete.setLayout(jPanel_deleteLayout);
        jPanel_deleteLayout.setHorizontalGroup(
            jPanel_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_deleteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel21)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel_deleteLayout.setVerticalGroup(
            jPanel_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_deleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        Form_nota.add(jPanel_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 287, -1, -1));
        Form_nota.add(jDateChooser_tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 250, -1));

        panel_frem.add(Form_nota, "card3");

        jPanel1.add(panel_frem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 105, -1, -1));

        btn_menu.setBackground(new java.awt.Color(255, 255, 255));
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menuMouseExited(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\logo\\menu_32px.png")); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_menuLayout = new javax.swing.GroupLayout(btn_menu);
        btn_menu.setLayout(btn_menuLayout);
        btn_menuLayout.setHorizontalGroup(
            btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btn_menuLayout.setVerticalGroup(
            btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 50));

        panel_menu.setBackground(new java.awt.Color(102, 102, 255));
        panel_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_menuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_menuMousePressed(evt);
            }
        });

        btn_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseClicked(evt);
            }
        });

        jLabel23.setText("PELANGGAN");

        javax.swing.GroupLayout btn_pelangganLayout = new javax.swing.GroupLayout(btn_pelanggan);
        btn_pelanggan.setLayout(btn_pelangganLayout);
        btn_pelangganLayout.setHorizontalGroup(
            btn_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_pelangganLayout.setVerticalGroup(
            btn_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_notaMouseClicked(evt);
            }
        });

        jLabel24.setText("NOTA");

        javax.swing.GroupLayout btn_notaLayout = new javax.swing.GroupLayout(btn_nota);
        btn_nota.setLayout(btn_notaLayout);
        btn_notaLayout.setHorizontalGroup(
            btn_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_notaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_notaLayout.setVerticalGroup(
            btn_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_notaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_nota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_id1ActionPerformed

    private void jTextField_nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nama1ActionPerformed

    private void jTextField_jumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_jumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_jumlah1ActionPerformed

    private void jTextField_total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_total1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_total1ActionPerformed

    private void btn_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_menuMouseEntered

    private void btn_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseExited
        // TODO add your handling code here:
         panel_menu.setSize(0, 0);
    }//GEN-LAST:event_btn_menuMouseExited

    private void btn_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseClicked
        // TODO add your handling code here:
         panel_menu.setSize(100, 200);
    }//GEN-LAST:event_btn_menuMouseClicked

    private void panel_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menuMouseEntered
        // TODO add your handling code here:
         panel_menu.setSize(100, 200);
    }//GEN-LAST:event_panel_menuMouseEntered

    private void panel_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menuMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_panel_menuMouseExited

    private void btn_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseClicked
        // TODO add your handling code here:
        
        //remove panel
        panel_frem.removeAll();
        panel_frem.repaint();
        panel_frem.revalidate();
        //add panel
        panel_frem.add(jPanel_pelanggan);
        panel_frem.repaint();
        panel_frem.revalidate();
    }//GEN-LAST:event_btn_pelangganMouseClicked

    private void btn_notaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_notaMouseClicked
        // TODO add your handling code here:
          //remove panel
        panel_frem.removeAll();
        panel_frem.repaint();
        panel_frem.revalidate();
        //add panel
        panel_frem.add(Form_nota);
        panel_frem.repaint();
        panel_frem.revalidate();
    }//GEN-LAST:event_btn_notaMouseClicked

    private void panel_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menuMousePressed
        // TODO add your handling code here:
          panel_menu.setSize(100, 200);
    }//GEN-LAST:event_panel_menuMousePressed

    private void jPanel_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_saveMouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("insert into tb_nota(idlangganan, nama, tanggal, jumlah_galon, total_harga) values(?,?,?,?,?)");
            stmt.setString(1, jTextField_id1.getText());
            stmt.setString(2, jTextField_nama1.getText());
            stmt.setString(3, jDateChooser_tgl1.getDateEditor().getUiComponent().toString());
            stmt.setString(4, jTextField_jumlah1.getText());
            stmt.setString(5, jTextField_total1.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jPanel_saveMouseClicked

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_namaActionPerformed

    private void jTextField_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_teleponActionPerformed

    private void jTextField_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_alamatActionPerformed

    private void jTextField_tempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tempatActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("insert into tb_langganan (idlangganan, nama, jenis_kelamin, telepon, alamat, jenis_tempat)values(?,?,?,?,?,?)");
            stmt.setString(1, jTextField_id.getText());
            stmt.setString(2, jTextField_nama.getText());
            stmt.setString(3, jComboBox_kelamin.getSelectedItem().toString());
            stmt.setString(4, jTextField_telepon.getText());
            stmt.setString(5, jTextField_alamat.getText());
            stmt.setString(6, jTextField_tempat.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here
        jTextField_id.setText("");
        jTextField_nama.setText("");
        jComboBox_kelamin.setSelectedItem("PILIH :");
        jTextField_telepon.setText("");
        jTextField_alamat.setText("");
        jTextField_tempat.setText("");
        jTextField_id.requestFocus();
    }//GEN-LAST:event_btn_addActionPerformed

    private void jTable_langgananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_langgananMouseClicked
        // TODO add your handling code here:
        int baris = jTable_langganan.getSelectedRow();
        jTextField_id.setText(DftTblModel_langganan.getValueAt(baris, 0).toString());
        jTextField_nama.setText(DftTblModel_langganan.getValueAt(baris, 1).toString());
        jComboBox_kelamin.setSelectedItem(DftTblModel_langganan.getValueAt(baris, 2).toString());
        jTextField_telepon.setText(DftTblModel_langganan.getValueAt(baris, 3).toString());
        jTextField_alamat.setText(DftTblModel_langganan.getValueAt(baris, 4).toString());
        jTextField_tempat.setText(DftTblModel_langganan.getValueAt(baris, 5).toString());
    }//GEN-LAST:event_jTable_langgananMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("update tb_langganan set nama=?, jenis_kelamin=?, telepon=?, alamat=?, jenis_tempat=? where idlangganan=?");
            stmt.setString(1, jTextField_id.getText());
            stmt.setString(2, jTextField_nama.getText());
            stmt.setString(3, jComboBox_kelamin.getSelectedItem().toString());
            stmt.setString(4, jTextField_telepon.getText());
            stmt.setString(5, jTextField_alamat.getText());
            stmt.setString(6, jTextField_tempat.getText());
            stmt.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable_langganan.getModel();
            model.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, "Data gagal diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        Connection conn = koneksi.getConnection();
             int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data tersebut?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
             if (confirm == 0) {
                 try {
                     java.sql.PreparedStatement stmt = conn.prepareStatement("delete from tb_langganan where idlangganan=' " + jTextField_id.getText()+"'");
                     stmt.executeUpdate();
                     JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                     TampilData();
                     jTextField_id.setText("");
                     jTextField_nama.setText("");
                     jComboBox_kelamin.setSelectedItem("PILIH :");
                     jTextField_telepon.setText("");
                     jTextField_alamat.setText("");
                     jTextField_tempat.setText("");
                     jTextField_id.requestFocus();
                 } catch (SQLException e) {
                     JOptionPane.showMessageDialog(null, "Data gagal di hapus" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
                 }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Form_nota;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JPanel btn_menu;
    private javax.swing.JPanel btn_nota;
    private javax.swing.JPanel btn_pelanggan;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> jComboBox_kelamin;
    private com.toedter.calendar.JDateChooser jDateChooser_tgl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_add;
    private javax.swing.JPanel jPanel_delete;
    private javax.swing.JPanel jPanel_pelanggan;
    private javax.swing.JPanel jPanel_save;
    private javax.swing.JPanel jPanel_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_langganan;
    private javax.swing.JTable jTable_nota;
    private javax.swing.JTextField jTextField_alamat;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_id1;
    private javax.swing.JTextField jTextField_jumlah1;
    private javax.swing.JTextField jTextField_nama;
    private javax.swing.JTextField jTextField_nama1;
    private javax.swing.JTextField jTextField_telepon;
    private javax.swing.JTextField jTextField_tempat;
    private javax.swing.JTextField jTextField_total1;
    private javax.swing.JPanel panel_frem;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
